execute pathogen#infect()

set nocompatible
set path+=**
set wildmenu
set exrc
set ruler
set showmode
set background=light
set tabstop=4
set shiftwidth=4
set autoindent
set smartindent
set cindent
set nowrap
set incsearch
set printoptions=paper:letter,duplex:off
set number
set numberwidth=5
set expandtab
set colorcolumn=80
set cursorline
syntax on

" trailing whitespace
match ErrorMsg '\s\+$'
match ErrorMsg '\t'

let mapleader = "\ "
nnoremap <Leader>o :o
nnoremap <Leader>r :r
nnoremap <Leader>x :x<CR>
nnoremap <Leader>w :w<CR>
nnoremap <Leader>q :q<CR>
nnoremap <Leader>e :e 
nnoremap <Leader>m :make<CR>
nnoremap <Leader>t <C-t>
nnoremap <Leader>] <C-]>
nnoremap <Leader>f :Vexplore<CR>
nnoremap <Leader>d :set background=dark<CR>
nnoremap <Leader>l :set background=light<CR>
nmap <Leader><Leader> V
inoremap ;; <ESC>

filetype plugin on

let g:airline_theme='minimalist'
